###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcwMzY5MzA3NywiZXhwIjoxNzExNDY5MDc3fQ.fG10Ce8iDSttNX74LlenPXK_ZBkb6VBKenhhUXHGgr0

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "j5@j3.com",
    "password": "Azerty123!",
    "birthDate": "2000-01-01",
    "address": "12 ave",
    "phone": "0458978456"
}

###
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcwMzY5MzA3NywiZXhwIjoxNzExNDY5MDc3fQ.fG10Ce8iDSttNX74LlenPXK_ZBkb6VBKenhhUXHGgr0

###
PATCH http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcwMzY5MzA3NywiZXhwIjoxNzExNDY5MDc3fQ.fG10Ce8iDSttNX74LlenPXK_ZBkb6VBKenhhUXHGgr0
Content-Type: application/json

{
    "password": "Doe23;:42"
}

###
DELETE http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcwMzY5MzA3NywiZXhwIjoxNzExNDY5MDc3fQ.fG10Ce8iDSttNX74LlenPXK_ZBkb6VBKenhhUXHGgr0

###
PATCH http://localhost:3000/users/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcwMzY5MzA3NywiZXhwIjoxNzExNDY5MDc3fQ.fG10Ce8iDSttNX74LlenPXK_ZBkb6VBKenhhUXHGgr0

{
    "lastname": "Doe2!1zez31425"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "j5@j3.com",
    "password": "Azerty123!"
}

### 
GET http://localhost:3000/bankaccounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcwMzY5MzA3NywiZXhwIjoxNzExNDY5MDc3fQ.fG10Ce8iDSttNX74LlenPXK_ZBkb6VBKenhhUXHGgr0

### Get par id
GET http://localhost:3000/bankaccounts/3


### 
POST http://localhost:3000/bankaccounts/
Content-Type: application/json

{
    "userId": 1
}

### 
PATCH http://localhost:3000/bankaccounts/2
Content-Type: application/json

{
    "balance": "1"
}

### 
DELETE http://localhost:3000/bankaccounts/3

### 
GET http://localhost:3000/creditcards

### GET carte par id
GET http://localhost:3000/creditcards/1

### Créer une CB
POST http://localhost:3000/creditcards/
Content-Type: application/json

{
  "userId": 1,
  "pin": "12345",
  "bankAccountId": 370867498
}


### DELETE carte par id 
DELETE http://localhost:3000/creditcards/3

###
GET http://localhost:3000/transactions

###
GET http://localhost:3000/transactions/1


###
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "senderAccountNumber": "370867498",
  "receiverAccountNumber": "492584425",
  "amount": 500
}


